# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RealLabsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'VungleAds'
  # Pods for RealLabsDemo

  target 'RealLabsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealLabsDemoUITests' do
    # Pods for testing
  end

end
